################################################################################
# Jenkins ServiceMonitor
# Scrapes metrics from Jenkins for Prometheus
################################################################################
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins
  namespace: monitoring
  labels:
    app: jenkins
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - devops
  selector:
    matchLabels:
      app.kubernetes.io/component: jenkins-controller
  endpoints:
    - port: http
      path: /prometheus
      interval: 30s
      scrapeTimeout: 10s

